# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'ClevertapiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for ClevertapiOS
pod "CleverTap-iOS-SDK"

  target 'ClevertapiOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'ClevertapiOSUITests' do
    # Pods for testing
  end

end
